### ISSUE TITLE
Test 'Use GPU' crashes if no GPU device was previously selected in the preferences

### ISSUE THREAD

**Issue by kiraacorsac** [kiraacorsac/PIGEOnS#1]
Replicate:

1) Make sure the new file does not pre-select cycles and a GPU device
2) Create new file
3) Switch to cycles
4) Run tests

```
Traceback (most recent call last):

  File "C:\Users\KiraaCorsac\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\muni_cz\pigeons\testRunner.py", line 32, in execute
    test.execute(context)

  File "C:\Users\KiraaCorsac\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\muni_cz\pigeons\tests.py", line 565, in execute
    bpy.context.preferences.addons.data.addons["cycles"].preferences[

KeyError: 'bpy_struct[key]: key "devices" not found'
```

![image](https://github.com/user-attachments/assets/4bd0a345-891d-455b-8016-4d80a9898de1)

**Comment by kiraacorsac** [comment]
fixed in 1.1.1
